#!/usr/bin/env tsx
/**
 * seed-products.ts
 *
 * Uploads product images to Supabase Storage and creates product/product_image
 * rows. Reads the canonical catalogue from /data/products.json and the optimised
 * variants + blurDataURLs from /data/optimised-images.json (generated by
 * scripts/optimise-images.mjs).
 *
 * Phase 1 only writes the JSON catalogue and prepares the variants. This script
 * is run in Phase 2 once the `products` and `product_images` tables exist.
 *
 * Usage:
 *   npm run seed
 *
 * Requires:
 *   .env.local with NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY
 *   Tables: products, product_images (created in Phase 2 migration)
 *   Storage bucket: dress-photos (public)
 */

import 'dotenv/config';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createClient } from '@supabase/supabase-js';

type Product = {
  slug: string;
  name: string;
  short_description: string;
  description: string;
  category: string;
  price: number;
  currency: string;
  primary_colour: string;
  available_sizes: string[];
  available_colours: string[];
  length: string;
  occasion: string[];
  featured: boolean;
  images: string[]; // paths relative to /public/assets/, e.g. "products/pink-mauve-mermaid/01.jpg"
};

type OptimisedImage = {
  source: string; // matches Product.images entries
  originalWidth: number;
  originalHeight: number;
  aspectRatio: number;
  variants: { filename: string; format: string; width: number }[];
  blurDataURL: string;
};

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const STORAGE_BUCKET = 'dress-photos';

if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);

async function loadCatalogue(): Promise<{ products: Product[]; optimised: Map<string, OptimisedImage> }> {
  const products: Product[] = JSON.parse(await readFile(resolve('data/products.json'), 'utf-8'));
  const optimisedList: OptimisedImage[] = JSON.parse(await readFile(resolve('data/optimised-images.json'), 'utf-8'));
  const optimised = new Map(optimisedList.map((o) => [o.source, o]));
  return { products, optimised };
}

async function uploadVariants(productImagePath: string, optimised: OptimisedImage) {
  const uploaded: { width: number; format: string; storage_path: string }[] = [];
  const sectionDir = productImagePath.split('/').slice(0, -1).join('/');

  for (const variant of optimised.variants) {
    const variantPath = resolve('public/assets/optimised', sectionDir, variant.filename);
    const buf = await readFile(variantPath);
    const storagePath = `${sectionDir}/${variant.filename}`;

    const { error } = await supabase.storage
      .from(STORAGE_BUCKET)
      .upload(storagePath, buf, { contentType: `image/${variant.format}`, upsert: true });

    if (error) {
      console.error(`  upload failed: ${storagePath} — ${error.message}`);
      continue;
    }
    uploaded.push({ width: variant.width, format: variant.format, storage_path: storagePath });
  }

  return uploaded;
}

async function seedProduct(product: Product, optimised: Map<string, OptimisedImage>, displayOrder: number) {
  console.log(`\n${product.name}`);

  const { data: inserted, error } = await supabase
    .from('products')
    .upsert(
      {
        slug: product.slug,
        name: product.name,
        short_description: product.short_description,
        description: product.description,
        category: product.category,
        price: product.price,
        currency: product.currency,
        primary_colour: product.primary_colour,
        available_sizes: product.available_sizes,
        available_colours: product.available_colours,
        length: product.length,
        occasion: product.occasion,
        featured: product.featured,
        display_order: displayOrder,
        active: true,
      },
      { onConflict: 'slug' }
    )
    .select()
    .single();

  if (error || !inserted) {
    console.error(`  product upsert failed: ${error?.message}`);
    return;
  }
  console.log(`  product upserted (id: ${inserted.id})`);

  for (let i = 0; i < product.images.length; i++) {
    const imagePath = product.images[i];
    const opt = optimised.get(imagePath);
    if (!opt) {
      console.warn(`  no optimised variants found for ${imagePath} — skip`);
      continue;
    }

    const variants = await uploadVariants(imagePath, opt);
    if (variants.length === 0) continue;

    // Pick the 1600px webp as canonical storage_path for product_images.storage_path.
    const canonical = variants.find((v) => v.width === 1600 && v.format === 'webp') ?? variants.at(-1)!;

    const { error: imgError } = await supabase
      .from('product_images')
      .upsert(
        {
          product_id: inserted.id,
          storage_path: canonical.storage_path,
          alt_text: `${product.name} — view ${i + 1}`,
          display_order: i,
          is_primary: i === 0,
          blur_data_url: opt.blurDataURL,
          aspect_ratio: opt.aspectRatio,
          variants: variants.map(({ width, format, storage_path }) => ({ width, format, storage_path })),
        },
        { onConflict: 'product_id,storage_path' }
      );

    if (imgError) console.error(`  image record failed: ${imgError.message}`);
    else console.log(`  image ${i + 1}/${product.images.length} (${variants.length} variants)`);
  }
}

async function main() {
  console.log('Seeding products into Supabase...');
  const { products, optimised } = await loadCatalogue();
  console.log(`Loaded ${products.length} products, ${optimised.size} optimised image records.`);

  for (let i = 0; i < products.length; i++) {
    await seedProduct(products[i], optimised, i + 1);
  }

  console.log('\nSeed complete.');
}

main().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
